"""new ORder table

Revision ID: bf6e376abb19
Revises: eb8bc83e1731
Create Date: 2023-08-21 18:46:21.740696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6e376abb19'
down_revision: Union[str, None] = 'eb8bc83e1731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('pizza_quantity', sa.Integer(), nullable=False),
    sa.Column('pizza_price', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('user', sa.Column('create_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_at')
    op.drop_column('user', 'notes')
    op.drop_table('order')
    # ### end Alembic commands ###
